# Generated by Django 3.2.9 on 2021-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tokeninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokeninfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='tokeninfo',
            name='account_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
