# Generated by Django 4.0.5 on 2022-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_userforminfo_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='gender',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
