# Generated by Django 4.0.5 on 2022-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_userforminfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='lucky_number',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
