# Generated by Django 4.0.5 on 2022-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_userforminfo_lucky_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='sent_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
