# Generated by Django 4.0.5 on 2022-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_userforminfo_sent_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='during_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total',
        ),
        migrations.AddField(
            model_name='campaign',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
