# Generated by Django 4.0.5 on 2022-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_campaign_during_date_remove_campaign_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_date',
        ),
    ]
