# Generated by Django 4.0.6 on 2022-07-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_delete_downloadinfo_delete_tokeninfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='lucky_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userforminfo',
            name='sent_status',
            field=models.CharField(max_length=50),
        ),
    ]
