# Generated by Django 4.0.6 on 2022-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_userforminfo_status_alter_userforminfo_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='file_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
