# Generated by Django 4.0.6 on 2022-07-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_campaign_file_name_alter_campaign_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='finished_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
