# Generated by Django 4.0.6 on 2022-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_schedule_finished_time_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='last_item',
            field=models.BooleanField(default=False),
        ),
    ]
