# Generated by Django 4.0.6 on 2022-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_userforminfo_last_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_schedules',
            field=models.IntegerField(default=0),
        ),
    ]
