# Generated by Django 4.0.6 on 2022-07-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_campaign_total_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleFormField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key_name', models.CharField(max_length=200)),
                ('google_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.googleforminfo')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.googleforminfo'),
            preserve_default=False,
        ),
    ]
