# Generated by Django 4.0.6 on 2022-07-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_googleforminfo_googleformfield_campaign_google_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='google_form',
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_form_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='googleforminfo',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.campaign'),
            preserve_default=False,
        ),
    ]
