# Generated by Django 4.0.6 on 2022-07-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_remove_userforminfo_age_remove_userforminfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleforminfo',
            name='name',
        ),
    ]
