# Generated by Django 4.0.6 on 2022-07-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_remove_googleforminfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleformfield',
            name='name',
        ),
    ]
