# Generated by Django 4.0.6 on 2022-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_remove_googleformfield_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformfield',
            name='key_index',
            field=models.IntegerField(default=1),
        ),
    ]
