# Generated by Django 4.0.6 on 2022-07-10 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_googleformfield_key_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformfield',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.campaign'),
            preserve_default=False,
        ),
    ]
