# Generated by Django 4.0.6 on 2022-07-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_googleformfield_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleforminfo',
            name='action_link',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='googleforminfo',
            name='fbzx',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='googleforminfo',
            name='fvv',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='googleforminfo',
            name='pageHistory',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='googleforminfo',
            name='partial_response',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userforminfo',
            name='field10',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userforminfo',
            name='field8',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userforminfo',
            name='field9',
            field=models.CharField(default='', max_length=200),
        ),
    ]
