# Generated by Django 4.0.6 on 2022-07-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_googleforminfo_action_link_googleforminfo_fbzx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforminfo',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
