# Generated by Django 4.0.6 on 2022-07-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_userforminfo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleforminfo',
            old_name='pageHistory',
            new_name='page_history',
        ),
    ]
