# Generated by Django 4.0.6 on 2022-07-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_rename_pagehistory_googleforminfo_page_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userforminfo',
            name='last_item',
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_item_id',
            field=models.IntegerField(default=-1),
        ),
    ]
