# Generated by Django 4.0.6 on 2022-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_remove_userforminfo_last_item_campaign_last_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_forms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_forms',
            field=models.IntegerField(default=0),
        ),
    ]
