# Generated by Django 4.1.7 on 2023-03-20 00:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0035_campaign_completed_forms_campaign_total_forms"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_id", models.CharField(max_length=1000)),
                ("file_desc", models.CharField(max_length=1000)),
                ("client_ip", models.CharField(default="", max_length=1000)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("download_count", models.IntegerField()),
                ("download_status", models.CharField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="TokenInfo",
            fields=[
                (
                    "account_id",
                    models.CharField(max_length=1000, primary_key=True, serialize=False),
                ),
                ("cookie_share_app", models.CharField(max_length=1000)),
                ("cookie_csrf", models.CharField(max_length=1000)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
            ],
        ),
    ]
