# Generated by Django 4.1.1 on 2022-09-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0035_campaign_completed_forms_campaign_total_forms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("text", models.CharField(default="", max_length=300, null=True)),
                ("date_timestamp", models.CharField(default="", max_length=300)),
                ("status", models.CharField(default="", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(default="", max_length=300)),
                ("firstname", models.CharField(default="", max_length=300, null=True)),
                ("lastname", models.CharField(default="", max_length=300, null=True)),
                ("username", models.CharField(default="", max_length=300, null=True)),
                ("status", models.CharField(default="", max_length=300)),
                ("ban_reason", models.CharField(default="", max_length=300)),
                ("isBot", models.BooleanField(default=False)),
                ("user_avatar_link", models.CharField(default="", max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="googleformfield",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="googleformfield",
            name="google_form",
        ),
        migrations.RemoveField(
            model_name="googleforminfo",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="userforminfo",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="GoogleFormField",
        ),
        migrations.DeleteModel(
            name="GoogleFormInfo",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="UserFormInfo",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.telegramuser"
            ),
        ),
    ]
