# Generated by Django 4.1.1 on 2022-09-16 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_message_telegramuser_remove_googleformfield_campaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("file_name", models.CharField(default="", max_length=300)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(default="", max_length=50)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("total_schedules", models.IntegerField(default=0)),
                ("total_forms", models.IntegerField(default=0)),
                ("completed_forms", models.IntegerField(default=0)),
                ("google_form_id", models.IntegerField(default=-1)),
                ("last_item_id", models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(default="", null=True),
        ),
        migrations.CreateModel(
            name="UserFormInfo",
            fields=[
                ("auto_increment_id", models.AutoField(primary_key=True, serialize=False)),
                ("field1", models.CharField(default="", max_length=200)),
                ("field2", models.CharField(default="", max_length=200)),
                ("field3", models.CharField(default="", max_length=200)),
                ("field4", models.CharField(default="", max_length=200)),
                ("field5", models.CharField(default="", max_length=200)),
                ("field6", models.CharField(default="", max_length=200)),
                ("field7", models.CharField(default="", max_length=200)),
                ("field8", models.CharField(default="", max_length=200)),
                ("field9", models.CharField(default="", max_length=200)),
                ("field10", models.CharField(default="", max_length=200)),
                ("status", models.CharField(default="", max_length=50)),
                ("sent", models.BooleanField(default=False)),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("sent_date_time", models.DateTimeField(blank=True, null=True)),
                ("sent_time", models.TimeField(blank=True, null=True)),
                ("sent_status", models.CharField(max_length=50)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.campaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(default="", max_length=50)),
                ("finished_time", models.TimeField(blank=True, null=True)),
                ("items", models.IntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.campaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleFormInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.CharField(default="", max_length=300)),
                ("action_link", models.CharField(default="", max_length=300)),
                ("num_fields", models.IntegerField(default=1)),
                ("partial_response", models.CharField(default="", max_length=300)),
                ("fbzx", models.CharField(default="", max_length=300)),
                ("fvv", models.CharField(default="", max_length=300)),
                ("page_history", models.CharField(default="", max_length=300)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.campaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleFormField",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key_name", models.CharField(max_length=200)),
                ("key_index", models.IntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.campaign"
                    ),
                ),
                (
                    "google_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.googleforminfo"
                    ),
                ),
            ],
        ),
    ]
