# Generated by Django 4.1.1 on 2022-10-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0038_telegramuser_profile_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=-1)),
                ("role", models.CharField(default="admin", max_length=50)),
                ("status", models.CharField(default="active", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="owner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="common.owner"
            ),
        ),
    ]
