# Generated by Django 4.1.1 on 2022-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_owner_campaign_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="campaign_id",
            field=models.IntegerField(default=-1),
        ),
    ]
