# Generated by Django 4.1.1 on 2022-10-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_owner_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="campaign_id",
        ),
    ]
