# Generated by Django 4.1.2 on 2022-10-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_remove_owner_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googleformfield",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="googleformfield",
            name="google_form",
        ),
        migrations.RemoveField(
            model_name="googleforminfo",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="userforminfo",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="GoogleFormField",
        ),
        migrations.DeleteModel(
            name="GoogleFormInfo",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="TelegramUser",
        ),
        migrations.DeleteModel(
            name="UserFormInfo",
        ),
    ]
