# Generated by Django 4.1.4 on 2022-12-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(default="", max_length=300)),
                ("firstname", models.CharField(default="", max_length=300, null=True)),
                ("lastname", models.CharField(default="", max_length=300, null=True)),
                ("username", models.CharField(default="", max_length=300, null=True)),
                ("status", models.CharField(default="", max_length=300)),
                ("ban_reason", models.CharField(default="", max_length=300)),
                ("isBot", models.BooleanField(default=False)),
                ("user_avatar_link", models.CharField(default="", max_length=300, null=True)),
                ("profile_score", models.CharField(default="", max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("text", models.TextField(default="", null=True)),
                ("date_timestamp", models.CharField(default="", max_length=300)),
                ("status", models.CharField(default="", max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="telegrambot.telegramuser"
                    ),
                ),
            ],
        ),
    ]
