# Generated by Django 4.1.1 on 2022-10-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.TextField(default="", null=True),
        ),
    ]
